# Generated by Django 3.2.6 on 2021-08-09 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=3, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Litery',
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Pseudonim')),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='Kategorie.kategoria')),
            ],
            options={
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Miasto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('slug', models.SlugField()),
                ('litera', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='Kategorie.letter')),
            ],
            options={
                'verbose_name_plural': 'Miasta',
            },
        ),
        migrations.AddField(
            model_name='kategoria',
            name='miasto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='Kategorie.miasto'),
        ),
    ]
